name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"   # Τρέχει κάθε 12 ώρες
  workflow_dispatch:           # Μπορείς να το τρέξεις χειροκίνητα
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: jsvgd7g655-alt
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
